// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.


public type attributeValue record {
    string startTime;
    string? endTime = ();
    string value;
};

public type metadataValue record {
    string kind?;
    string birthDate;
    string? deathDate = ();
};


//public type inline_response_200_1 record {string 'start?; string? end?; string value?;}|record {string 'start?; string? end?; string value?;}[]|string?;


